use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

config :link, LinkWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  force_ssl: []

config :core, Core.SurfConext,
  site: "https://connect.test.surfconext.nl",
  redirect_uri: "https://localhost/surfconext/auth"

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
# SSL should be terminated by the load-balancer / proxy server. The following
# setting makes sure that users do not connect over plain HTTP.
# config :link, CoreWeb.Endpoint, force_ssl: [rewrite_on: [:x_forwarded_proto]]
config :link, :ssl, directory_url: "https://acme-staging-v02.api.letsencrypt.org/directory"
