#!/bin/bash

set -e
set -x

if [ -z ${VERSION} ]; then
    echo "VERSION is unset"
    exit 1
fi
if [ -z ${BUNDLE} ]; then
    echo "BUNDLE is unset"
    exit 1
fi

cd $(dirname "$0")/..

mix deps.get
mix assets.setup
mix assets.deploy

MIX_ENV=prod mix release --overwrite --path "${VERSION}"

chmod -R a+rX "${VERSION}"
