name: "Mix Dependency Submission Update"

on:
  workflow_dispatch:
    inputs:
      install-deps: true

permissions:
  contents: write

jobs:
  report_mix_deps:
    name: "Report Mix Dependencies"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/mix-dependency-submission@v1
