name: "Mix Dependency Submission"

on:
  workflow_dispatch:
    inputs:
      install-deps:
        type: bool
        default: true
        required: false

permissions:
  contents: write

jobs:
  report_mix_deps:
    name: "Report Mix Dependencies"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/mix-dependency-submission@v1
